[package]
name = "nj-example-hello-async-cb"
version = "0.0.1"
authors = ["fluvio.io"]
edition = "2018"


[lib]
crate-type = ["cdylib"]


[dependencies]
libc = "0.2.66"
nj-core = { path = "../nj-core"}
flv-future-core = { path = "../../future-helper" }