[workspace]
members = [
    "src/cli",
    "src/client",
    "src/future-aio",
    "src/future-helper",
    "src/api/internal-api",
    "src/k8-client",
    "src/k8-config",
    "src/k8-diff",
    "src/kf-protocol",
    "src/kf-protocol/kf-protocol-dump",
#    "kf-protocol/kf-protocol-build",
    "src/kf-socket",
    "src/kf-service",
    "src/k8-metadata",
    "src/metadata",
    "src/api/sc-api",
    "src/sc-core",
    "src/sc-k8",
    "src/api/spu-api",
    "src/spu-server",
    "src/storage",
    "src/test-helper",
    "src/types",
    "src/utils",
    "src/nj-sys"
]

# profile to make image sizer smaller
# comment out for now
#[profile.release]
#lto = true
#codegen-units = 1
#incremental = false