[package]
name = "fluvio"
version = "0.2.1"
edition = "2018"
authors = ["fluvio.io"]


[[bin]]
name = "fluvio"
path = "src/bin/main.rs"
doc = false


[dependencies]
log = "0.4.8"
bytes = "0.5.3"
structopt = { version = "0.2.14", default-features = false }
toml = "0.5.5"
prettytable-rs = "0.8.0"
rand = "0.7.2"
serde = { version ="1.0.103", features = ['derive'] }
serde_json = "1.0.39"
serde_yaml =  "0.8.8"
async-trait = "0.1.21"
ctrlc = "3.1.3"
regex = "1.3.1"
futures = { version = "0.3.1", features = ['async-await'] }
flv-future-core = { path = "../future-helper" }
flv-future-aio = { path = "../future-aio"}
utils = { path= "../utils"}
types = { path ="../types"}
kf-protocol = { path = "../kf-protocol"}
kf-socket = { path = "../kf-socket" }
k8-metadata = { path = "../k8-metadata"}
sc-api = { path = "../api/sc-api"}
spu-api = { path = "../api/spu-api"}
flv-client = { path = "../client-rs"}

