[package]
name = "nj-core"
version = "0.2.1"
authors = ["fluvio.io"]
edition = "2018"

[dependencies]
log = "0.4.8"
ctor = "0.1.12"
byte-strings = "0.1.3"
libc = "0.2.66"
async-trait = "0.1.22"
nj-sys = { path = "../nj-sys" }
flv-future-core = { path = "../../future-helper" }