[package]
name = "nj-example-wrapper"
version = "0.0.1"
authors = ["fluvio.io"]
edition = "2018"


[lib]
crate-type = ["cdylib"]


[dependencies]
nj-core = { path = "../nj-core"}
nj-sys = { path = "../nj-sys" }