[package]
name = "flv-client"
version = "0.2.1"
edition = "2018"
authors = ["fluvio.io"]
license = "Apache-2.0"
repository = "https://github.com/infinyon/fluvio"
homepage = "fluvio.io"
description = "Client for Fluvio"
categories = ["stream", "fluvio", "client","stateful"]

[dependencies]
log = "0.4.8"
rand = "0.7.2"
dirs = "1.0.2"
toml = "0.5.5"
futures = { version = "0.3.1", features = ['async-await'] }
async-trait = "0.1.21"
serde = { version ="1.0.103", features = ['derive'] }
serde_json = "1.0.39"
flv-future-core = { path = "../future-helper" }
flv-future-aio = { path = "../future-aio"}
kf-protocol = { path = "../kf-protocol"}
types = { path = "../types"}
kf-socket = { path = "../kf-socket" }
sc-api = { path = "../api/sc-api"}
spu-api = { path = "../api/spu-api"}

